name: core
description: "Core component of an application"
version: 0.0.1

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^16.1.0
  logging: ^1.3.0
  get_it: ^8.2.0
  intl: ^0.20.2
  http: ^1.5.0
  collection: ^1.19.1
  async: ^2.13.0
  url_launcher: ^6.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0