name: ui
description: "Design system for an application"
version: 0.0.1
publish_to: none


environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../core
  shimmer: ^3.0.0
  flutter_animate: ^4.5.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
